### ISSUE TITLE
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Illagers+ (illagers_plus) Caused by: java.lang.NoSuchMethodError: net.minecraft.util.text.translation.I18n.translateToLocal(Ljava/lang/String;)Ljava/lang/String;

### ISSUE THREAD

**Issue by a-frenzy** [LiteWolf101/IllagersPlus#1]
https://gist.github.com/frenzye/ffee9ff42e5d0c823c595cd0ea60b0f5

**Comment by brisingraerowing** [comment]
Getting this as well.

**Comment by LiteWolf101** [comment]
Make sure to use the format posted on the front page. I have no idea what version of Illagers+ is causing this issue.

**Comment by LiteWolf101** [comment]
Bug should be fixed in the newest release.
https://www.curseforge.com/minecraft/mc-mods/illagers/files/2750468
