### ISSUE TITLE
Loot tables

### ISSUE THREAD

**Issue by a-frenzy** [LiteWolf101/IllagersPlus#2]
Hi, 

I noticed at one point Illagers Plus was adding loot tables vanilla style, well it's hard for me to explain, exactly how Illagers Plus was adding loot tables, but if I did the Crafttweaker command /ct loottables all - the Illagers Plus entities and structures were listed in the dump as being registered in this way https://i.imgur.com/ZSO1r6u.png There was a "Illagers Plus" folder there with "entities" and "structures" folders inside which listed all of the mods entities and structures 

So,  I wrote some crafttweaker scripts to integrate the Illagers structures (rare, normal) and entities into my pack by giving them drops and loot from the other mods, but for some reason Illagers Plus isn't registering it's loot in this way anymore, do you have any idea?

Is there a way to turn that back on, or, add a config option to add to loot to the different Illagers structures? 

https://gist.github.com/frenzye/839d90acbf55063b6ebb64f888b6294f

**Comment by LiteWolf101** [comment]
Yes, the Illagers+ loot tables are registered and loaded vanilla style. I don't know how they would disappear like that. I've never used Crafttweaker so I don't really know much how code function on their end, but I can guarantee you that the loot tables exist. Does this issue also happen with vanilla loot tables?
