### ISSUE TITLE
Suggestion: Biome Spawning Support

### ISSUE THREAD

**Issue by Yourname942** [LiteWolf101/IllagersPlus#4]
For 1.12.2 I have two suggestions:

1) biome support for:
- [Biomes O Plenty](https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty)
- [The Defiled Lands](https://www.curseforge.com/minecraft/mc-mods/defiled-lands)

Issue:
At the moment, the archer tower, the illager centre, and the illager tower can only spawn in vanilla biomes.
    - With Biomes O Plenty and the Defiled Lands the chances of finding a vanilla biome are slim 
    - Increasing the spawn rate just makes them spawn a ton in a small cluster (ie. The spawns aren't evenly distributed between biomes)

2) Add a blacklist of biomes to the config, in which they cannot spawn 

Thank you. I would gladly help test your code if you let me.

**Comment by LiteWolf101** [comment]
Feature has been changed and fixed in later versions
