### ISSUE TITLE
Slightly silly generation

### ISSUE THREAD

**Issue by brisingraerowing** [LiteWolf101/IllagersPlus#5]
![2019-12-21_10 47 26](https://user-images.githubusercontent.com/250409/71310214-6c4ebc80-23df-11ea-902d-db5089b24d10.png)

Not sure if anything can actually be done about it. Just looks silly.

**Comment by brisingraerowing** [comment]
![2019-12-21_10 49 25](https://user-images.githubusercontent.com/250409/71310228-93a58980-23df-11ea-920a-c870688f1b5b.png)

And another.

**Comment by LiteWolf101** [comment]
Thanks for letting me know

**Comment by LiteWolf101** [comment]
Fixed 1.16.4
