### ISSUE TITLE
Mobs too easy to kill.

### ISSUE THREAD

**Issue by Garfink** [LiteWolf101/IllagersPlus#7]
Illagers Version 1.1.3 - 1.12.2 on Forge 1.12.2-14.23.5.2838

We've discovered the mob balance is off, we were able to kill the illagers easily with early iron weapons, can't imagine how non-scalable it will be with modded weapons.  I was wondering if you could add a config that allows us to increase the damage dealt and health of the illagers?

A difficulty slider of sorts.  

Thanks in advance.

**Comment by LiteWolf101** [comment]
Not adding a config to adjust each mob attribute. That's way too much unnecessary work. Besides, more often then not, balancing in mods is hard to control when you have OP weapons. In this case, I'd suggest looking to one of McJty's mods or something else to handle that.
